const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const userSchema = new Schema({
    name: {
        type: String,
        required: true
    },
    email: {
        type: String,
        unique: true,
        required: true,
        lowercase: true
    },
    password: {
        type: String,
        // minlength: [6, 'Password should be at least 6 characters long'],
        // maxlength: [1024, "Password can't exceed more than 512 character"],
        // trim: true,
        required: true
    },
    categories: {
        type: Array,
        default: []
    },
    tasks: {
        type: Array,
        default: []
    },
    verKey: {
        type: String,
    },
    isVerified: {
        type: Boolean,
        default: false
    }
}, {
    timestamps: true, // adds createdAt and updatedAt fields to the schema
    // versionKey:false,   // removes _v field from documents (to avoid conflicts with other versions
    // id:false,           // remove __id field generated by mongoDB when using findOneAndUpdate()
});

module.exports = mongoose.model('User', userSchema);